apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.secret.name }}
type: Opaque
data:
  host: {{ .Values.backend.secret.host | b64enc }}
  port: {{ .Values.backend.secret.port | b64enc }}
  username: {{ .Values.backend.secret.username | b64enc }}
  password: {{ .Values.backend.secret.password | b64enc }}
  database: {{ .Values.backend.secret.database | b64enc }}